# Generated by Django 2.2 on 2019-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0002_formateur_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='googleplus_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='gsm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='linkdin_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='mes_images/'),
        ),
        migrations.AddField(
            model_name='formateur',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
