# Generated by Django 2.2 on 2019-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0003_auto_20190516_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
