# Generated by Django 2.2 on 2019-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateurs', '0004_formateur_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='etablissement_scolaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='methodologie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='niveau_etude',
            field=models.CharField(choices=[('secondaire', 'Secondaire'), ('universitaire', 'Universitaire'), ('professionnel', 'Professionnel')], default='secondaire', max_length=200),
        ),
        migrations.AddField(
            model_name='formateur',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
