# Generated by Django 2.2 on 2019-08-01 09:29

from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(choices=[('ba1', 'BA1'), ('ba2', 'BA2'), ('ba3', 'BA3'), ('ma1', 'MA1'), ('ma2', 'MA2')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mes_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mes_images/')),
                ('univerite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprenants.University')),
            ],
        ),
    ]
