# Generated by Django 2.2 on 2019-08-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annee',
        ),
    ]
