# Generated by Django 2.2 on 2019-08-01 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apprenants', '0002_delete_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('gsm', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='mes_images/')),
                ('categorie', models.CharField(max_length=200)),
                ('annee', models.CharField(choices=[('ba1', 'BA1'), ('ba2', 'BA2'), ('ba3', 'BA3'), ('ma1', 'MA1'), ('ma2', 'MA2')], max_length=30)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprenants.Faculte')),
                ('universite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprenants.University')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
