# Generated by Django 2.2 on 2019-08-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0003_apprenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculte',
            old_name='nom',
            new_name='nom_complet',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='nom',
            new_name='nom_complet',
        ),
        migrations.AddField(
            model_name='faculte',
            name='abreviation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='abreviation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
