# Generated by Django 2.2 on 2019-08-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apprenants', '0004_auto_20190801_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculte',
            old_name='univerite',
            new_name='universite',
        ),
    ]
