# Generated by Django 2.2 on 2019-05-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cours',
        ),
    ]
