# Generated by Django 2.2 on 2019-05-10 12:07

from django.db import migrations, models
import fontawesome.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0002_delete_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
        ),
    ]
