# Generated by Django 2.2 on 2019-05-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0005_skillcours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('prerequis', models.TextField()),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Cours')),
            ],
        ),
    ]
