# Generated by Django 2.2 on 2019-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_lecon'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='titre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
