# Generated by Django 2.2 on 2019-05-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_lecon_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(upload_to='mes_images/'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('tarif', models.CharField(max_length=10)),
                ('capacite', models.PositiveSmallIntegerField(default=3)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Cours')),
            ],
        ),
    ]
