# Generated by Django 2.2 on 2019-05-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0008_auto_20190513_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='cours',
        ),
        migrations.AddField(
            model_name='cours',
            name='total',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='option',
            name='lecon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cours.Lecon'),
        ),
    ]
