# Generated by Django 2.2 on 2019-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0012_auto_20190520_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='courte_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cours',
            name='long_description',
            field=models.TextField(),
        ),
    ]
