# Generated by Django 2.2 on 2019-05-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0013_auto_20190520_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='courte_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cours',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
