# Generated by Django 2.2 on 2019-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0014_auto_20190520_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecon',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='prerequis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
