# Generated by Django 2.2 on 2019-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0015_auto_20190520_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecon',
            options={'ordering': ('ordre',)},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('debut',)},
        ),
        migrations.AlterField(
            model_name='skillcours',
            name='skill',
            field=models.TextField(blank=True, null=True),
        ),
    ]
