# Generated by Django 2.2 on 2019-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0017_reviewcours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
