# Generated by Django 2.2 on 2019-06-03 15:23

from django.db import migrations, models
import django.db.models.deletion
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0018_cours_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='mes_images/')),
                ('description', models.TextField()),
                ('icon', fontawesome.fields.IconField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CibleCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Cible')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Cours')),
            ],
        ),
    ]
