# Generated by Django 2.2 on 2019-06-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0019_cible_ciblecours'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mes_images/'),
        ),
    ]
