# Generated by Django 2.2 on 2019-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0020_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateurcours',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
