# Generated by Django 2.2 on 2019-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0021_formateurcours_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cible',
            options={'ordering': ('ordre',)},
        ),
        migrations.AddField(
            model_name='cible',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='formateurcours',
            name='main',
            field=models.BooleanField(default=True),
        ),
    ]
