# Generated by Django 2.2 on 2019-06-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0022_auto_20190604_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecon',
            name='prerequis',
        ),
        migrations.AddField(
            model_name='cours',
            name='prerequis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
