# Generated by Django 2.2 on 2019-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0027_auto_20190801_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='annee',
            field=models.CharField(blank=True, choices=[('ba1', 'BA1'), ('ba2', 'BA2'), ('ba3', 'BA3'), ('ma1', 'MA1'), ('ma2', 'MA2')], max_length=20, null=True),
        ),
    ]
