# Generated by Django 2.2 on 2019-08-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_categoriefaq2_faq2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq2',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.CategorieFaq2'),
        ),
        migrations.DeleteModel(
            name='CategorieFaq',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
