# Generated by Django 2.2 on 2019-08-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_auto_20190805_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategorieFaq2',
            new_name='CategorieFaq',
        ),
        migrations.RenameModel(
            old_name='Faq2',
            new_name='Faq',
        ),
    ]
